INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(1, 'Dashboard', 'dashboard', 'admin/dashboard', 'fa fa-dashboard', '');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(2, 'Settings', 'settings', '#', 'fa fa-gears', '');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(3, 'Website', 'website', 'admin/settings/website', 'fa fa-circle-o', 'settings');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(4, 'Apperance', 'apperance', 'admin/settings/apperance', 'fa fa-circle-o', 'settings');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(5, 'Advertising', 'advertising', 'admin/settings/advertising', 'fa fa-circle-o', 'settings');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(6, 'Email Service (SMTP)', 'emailservice', 'admin/settings/emailservice', 'fa fa-circle-o', 'settings');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(9, 'Stations', 'stations', 'admin/stations', 'fa fa-headphones', '');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(10, 'Users', 'users', 'admin/users', 'fa fa-users', '');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(11, 'Translation', 'translation', 'admin/translation', 'fa fa-language', '');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(12, 'External Services', 'externalservices', 'admin/externalservices', 'fa fa-puzzle-piece', '');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(13, 'Music', 'music', '#', 'fa fa-music', '');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(14, 'Lyrics', 'lyrics', 'admin/music/lyrics', 'fa fa-circle-o', 'music');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(15, 'Artist', 'artist', 'admin/music/artist', 'fa fa-circle-o', 'music');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(16, 'Track', 'track', 'admin/music/track', 'fa fa-circle-o', 'music');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(17, 'Album', 'album', 'admin/music/album', 'fa fa-circle-o', 'music');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES(18, 'Base Links (SEO)', 'baselinks', 'admin/settings/slug', 'fa fa-circle-o', 'settings');
INSERT INTO `{prefix}admin_menus` (`idmenu`, `title`, `idunique`, `target`, `icon`, `idparent`) VALUES (NULL, 'Updates', 'update', 'admin/update', 'fa fa-upload', '');
INSERT INTO `{prefix}settings` VALUES('site_title', '', 'Title Website', '', 'text', '', 'required="required"', '', 'website', 1);
INSERT INTO `{prefix}settings` VALUES('lastfm_apikey', '', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('youtube_apikey', '', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('slug_main', 'artist', 'Root', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_playlist', 'playlist', 'Playlist', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_user', 'user', 'User', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_station', 'stations', 'Stations', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_trending', 'trending-now', 'Trending Now', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('site_description', '', 'Description', '', 'text', '', 'required="required"', '', 'website', 2);
INSERT INTO `{prefix}settings` VALUES('slug_login', 'login', 'Login', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_register', 'register', 'Register', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_logout', 'logout', 'Logout', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_my_playlist', 'myplaylists', 'My Playlists', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('theme', 'default', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('radionomy_apikey', '', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('color_scheme', 'green', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('ads_slot1', '', 'ADS #1', '', 'textarea', '', '', '', 'advertising', 0);
INSERT INTO `{prefix}settings` VALUES('ads_slot2', '', 'ADS #2', '', 'textarea', '', '', '', 'advertising', 0);
INSERT INTO `{prefix}settings` VALUES('keywords', '', 'Keywords', '', 'text', '', '', 'select2', 'website', 3);
INSERT INTO `{prefix}settings` VALUES('force_login', '0', 'Force Login', '', 'select', 'Yes:1|No:0', '', 'select2', 'website', 6);
INSERT INTO `{prefix}settings` VALUES('download_services', 'apple,amazon,youtube,soundcloud,spotify', 'Download Services', '', 'select-multiple', 'iTunes:apple|Amazon:amazon|Youtube:youtube|Soundcloud:soundcloud|Spotify:spotify', '', 'select2', 'website', 5);
INSERT INTO `{prefix}settings` VALUES('download_button', '2', 'Download Button', '', 'select', 'Only Registered:2|All:1|Hide:0', '', 'select2', 'website', 4);
INSERT INTO `{prefix}settings` VALUES('streaming_engine', 'youtube,soundcloud', 'Streaming Engine', 'What engine do you want use for streaming music', 'select-multiple', 'Youtube:youtube|SoundCloud:soundcloud', '', 'select2', 'website', 4);
INSERT INTO `{prefix}settings` VALUES('show_video', '1', 'Show Video Youtube', 'Show or hide video youtube', 'select', 'Show:1|Hide:0', '', 'select2', 'apperance', 1);
INSERT INTO `{prefix}settings` VALUES('slug_top_playlist', 'top-playlists', 'Top Playlists', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_my_favorites', 'my-favorites', 'My Favorires', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('facebook_app_id', '', 'Facebook APP ID', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('facebook_app_secret', '', 'Facebook APP Secret', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('google_client_id', '', 'Google Client ID', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('google_client_secret', '', 'Google Client Secret', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('spotify_client_id', '', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('spotify_client_secret', '', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('ads_slot3', '', 'ADS #3', '', 'textarea', '', '', '', 'advertising', 0);
INSERT INTO `{prefix}settings` VALUES('logo', 'assets/images/logo.png', 'Logo', '', '', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('vk_client_id', '', 'VK Client ID', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('vk_client_secret', '', 'VK Client Secret', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('musixmatch_apikey', '', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('trending_tracks_source', 'local', 'Trending Tracks', 'Musixmatch: Required api key', 'select', 'Local:local|Musixmatch:musixmatch', '', 'select2', 'website', 4);
INSERT INTO `{prefix}settings` VALUES('slug_genres', 'genres', 'Genres', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('slug_new_releases', 'new-releases', 'New Releaeses', '', 'text', '', 'required="required"', '', 'slug', 0);
INSERT INTO `{prefix}settings` VALUES('purchase_code', '', 'Purchase Code', '', 'text', '', 'required="required"', '', '', 1);
INSERT INTO `{prefix}settings` VALUES('soundcloud_client_id', '', 'Soundcloud Client ID', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('soundcloud_client_secret', '', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('itunes_afiliate', '10lJNg', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('amazon_afiliate', 'anthmu-20', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('amazon_site', 'http://www.amazon.com', '', '', 'text', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('proxy', '', 'CURL Proxy', '', 'text', '', 'placeholder="IP:PORT"', '', 'website', 7);
INSERT INTO `{prefix}settings` VALUES('homepage', 'slug_new_releases', 'Homepage', '', 'select', 'Stations:slug_station|Trending:slug_trending|Login:slug_login|Register:slug_register|Genres:slug_genres|New Release:slug_new_releases', '', 'select2', 'website', 8);
INSERT INTO `{prefix}settings` VALUES('smtp_host', '', 'Host', '', 'text', '', 'required="required"', '', 'emailservice', 1);
INSERT INTO `{prefix}settings` VALUES('smtp_port', '', 'Port', '', 'numeric', '', 'required="required"', '', 'emailservice', 2);
INSERT INTO `{prefix}settings` VALUES('smtp_user', '', 'Username', '', 'text', '', 'required="required"', '', 'emailservice', 3);
INSERT INTO `{prefix}settings` VALUES('smtp_password', '', 'Password', '', '', '', 'required="required"', '', 'emailservice', 5);
INSERT INTO `{prefix}settings` VALUES('smtp_from', '', 'From Email', '', 'text', '', 'required="required"', '', 'emailservice', 5);
INSERT INTO `{prefix}settings` VALUES('smtp_crypto', '', 'Smtp Crypto', '', 'select', 'TLS:tls|SSL:ssl', 'required="required"', 'select2', 'emailservice', 2);
INSERT INTO `{prefix}settings` VALUES('ga', '', 'Google Analytics', 'UA-XXXXXXX-X code', 'text', '', '', '', 'website', 5);
INSERT INTO `{prefix}settings` VALUES('gwt', '', 'Google Code Verification', '', 'text', '', '', '', 'website', 3);
INSERT INTO `{prefix}settings` VALUES('update_hash', '', '', '', '', '', '', '', '', 0);
INSERT INTO `{prefix}settings` VALUES('version', '', '', '', '', '', '', '', '', 0);
